---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-console
  labels:
    app: cloud-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-console
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-console
    spec:
      restartPolicy: Always
      containers:
      - name: cloud-console
        image: cloudconsole.registry.com:5000/cloud-console:v1
        imagePullPolicy: Always
        command:
          - /bin/sh
          - "-c"
          - "while :;do sleep 10; done"
