---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-console
rules:
- apiGroups:
  - ""
  resources:
    - pods
  verbs:
    - get
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - create
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-console
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user1
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group1
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group2
## Uncomment the following lines if you want to allow the access for all the authenticated Users.
#- apiGroup: rbac.authorization.k8s.io
#  kind: Group
#  name: system:authenticated
